### ISSUE TITLE
History Back/Forward

### ISSUE THREAD

**Issue by AugmentBLU** [Behavior-UI/behavior-ui#67]
Hello,

just wondering if there's a fix for the history usage for the Ajax trigger. When using updateHistory, clicking the back or forward button in the browser doesn't work. 

Thanks!

**Comment by anutron** [comment]
In theory, the way things are supposed to work with that feature is that the ajax request for the link grabs the full page and filters out just the section you wish to update (or your server detects it's an XHR and serves only the appropriate fragment). If the user were to hit reload, they'd get the same page they're looking at. But back button behavior should, in theory, be a full page reload. I.e. if the user loads /foo, then clicks /bar, your ajax delegator trigger should request /bar, then filter out everything in the response except the section you wish to update. Hitting reload would give you /bar in the same state. Hitting back would go to /foo and you'd get /foo in the same state you got it the first time.

So that being the case I've added support for reloading the page when that happens: https://github.com/Behavior-UI/behavior-ui/pull/66

You can do this yourself easily enough without waiting for this to be released. Just add this to your page:

```
window.addEvent('popstate', function(){
  window.location.href = window.location.href;
})
```

**Comment by anutron** [comment]
@AugmentBLU this has been released!

**Comment by AugmentBLU** [comment]
Awesome Aaron, much appreciated.
