### ISSUE TITLE
Delegator.register OnComplete?

### ISSUE THREAD

**Issue by AugmentBLU** [Behavior-UI/behavior-ui#71]
Hello,

I'm trying to trigger a function after a delegator has completed its task but I can't seem to see how this is done. 

An example would be using the Trigger delegator and ajax, for the function to fire after the ajax request has completed. What I have below does work but triggers immediately after the click rather than waiting for the response.  

HTML
`data-behavior="Trigger" data-trigger-options="'triggers': [{'events': ['click'],'targets': {'a': {'self::ajax': {'updateHistory': true,'useSpinner': true,'action': 'replace','target': '!body .replace-container','filter': '.replace-container'}}}}]" data-trigger="onComplete" data-oncomplete-target="'!body .replace-container"`

JS
`Delegator.register('click', {
  'onComplete': {      
    handler: function(event, element, api){
      // I want to trigger here after the ajax request      
    }
  }
});`

Any help would be great.

Thanks!

**Comment by anutron** [comment]
The "behavior way" of doing this would be to have a `Behavior.Startup` value in the response. There are mechanisms in Behavior that allow you to attach events, but not to Delegator triggers.

Behavior filters have a convention that they return an instance of something. Their purpose is explicitly to instantiate classes. Delegator triggers though often just invoke a method (for example, the `addClass` trigger).

The `Ajax` trigger, for example, has a `throttle` option that prevents it from sending too often, and a `once` option that prevents it from sending repeatedly, and in both cases no `Request` instance is even created, so there's nothing it could return even if it wanted to.

Behavior filters, on the other hand, actually store the instance of the thing they instantiate (retrievable by `Element.getBehaviorResult('BehaviorName')`), and Behavior plugins rely on that instance being returned precisely to allow you to add events or call methods on them. This is also because Behavior plugins and Delegator triggers don't have any promise of order; i.e. if an element has a behavior for turning a form into an ajax form, AND it has a form validator behavior, which prevents the user from submitting a form that has invalid inputs, there's no promise that the validator would be instantiated before the ajax controller, so they can't know about each other. This is what Behavior plugins are for; they allow you to assert that a plugin is ALWAYS instantiated after a filter.

This is a bit long winded though; sorry. I'm just trying to explain why Behavior filters have an events model in Behavior.Event, and why Delegator triggers don't.

The right way to do this then is with `Behavior.Startup` in your ajax response. You can do a lot with these. Namely:
* You could use `Delegator.Invoke` to invoke an element method
* Behavior.Startup invokes any delegator trigger, passing arguments and everything, so you can invoke any delegator you like.
* You could write a custom Behavior filter to do anything, including finding another Behavior filter's instance with `Element.getBehaviorResult` and invoking its methods
etc...

**Comment by anutron** [comment]
Gonna close the issue, but feel free to keep the thread going.

**Comment by anutron** [comment]
Also, note that when you invoke a Delegator trigger w/ `Behavior.Startup` you can have conditionals and that you can invoke more than one. So, for example, you could have the user click a link, load its ajax response, and in that response you could find one element and add a class, find another element, and reveal it, find another element and give it focus, set it's inner HTML w/ `set`, whatever.
